version: '3'

services:
  nifi:
    cap_add:
      - NET_ADMIN # low port bindings
    image: apache/nifi
    container_name: nifi
    ports:
      - 8080:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    networks:
      - nifinet
networks:
  nifinet:
    driver: bridge