VAGRANTFILE_API_VERSION = "2"

cluster = {
  "apache-nifi" => { :ip => "192.168.1.20", :cpus => 2, :memory => 4096 },
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  cluster.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|
      cfg.vm.box = "bento/ubuntu-20.04"
      cfg.vm.hostname = hostname
      cfg.vm.network :private_network, ip: info[:ip]
      cfg.vm.synced_folder ".", "/vagrant", disabled: true
      cfg.vm.provision :docker

      cfg.vm.provider :virtualbox do |vb|
        vb.name = hostname
        vb.cpus = info[:cpus]
        vb.memory = info[:memory]
        vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      end # end of vb
    end # end cfg
  end # end cluster
end
